# Nota: Execute este comando no host: sudo sysctl -w vm.overcommit_memory=1

services:
  init-volumes:
    image: busybox
    container_name: init-volumes
    command: >
      sh -c "
      mkdir -p /data/mysql /data/redis /logs/redis /data/grafana &&
      chmod -R 777 /data
      "
    volumes:
      - ./data:/data
    networks:
      - network

  database:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: home
      MYSQL_USER: home
      MYSQL_PASSWORD: home
      MYSQL_ROOT_PASSWORD: home
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    mem_limit: 2g
    cpus: 2.0
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: home
    depends_on:
      - database
    restart: always
    mem_limit: 1g
    cpus: 1.0
    networks:
      - network

  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--protected-mode", "no", "--requirepass", "redis"]
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./logs/redis:/var/log/redis
    depends_on:
      - init-volumes
    restart: always
    mem_limit: 1g
    cpus: 2.0
    networks:
      - network

  redisinsight:
    image: redis/redisinsight:2.68
    container_name: redis-insight
    depends_on:
      - redis
    ports:
      - "5540:5540"
    restart: always
    mem_limit: 1g
    cpus: 1.0
    networks:
      - network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - mysqld_exporter
    mem_limit: 1g
    cpus: 1.0
    networks:
      - network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - prometheus
      - init-volumes
    restart: always
    mem_limit: 1g
    cpus: 1.0
    networks:
      - network

  mysqld_exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    command:
      - "--config.my-cnf=/etc/.my.cnf"
    volumes:
      - ./exporter/.my.cnf:/etc/.my.cnf:ro
    depends_on:
      - database
    ports:
      - "9104:9104"
    restart: always
    mem_limit: 200m
    cpus: 0.5
    networks:
      - network

  node_exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always
    mem_limit: 200m
    cpus: 0.5
    networks:
      - network

networks:
  network: